import request from '@/utils/request'
export const getOverview = () => request.get('/admin/dashboard/overview')
export const getMistakeStats = () => request.get('/admin/mistakes/stats')
export const getLogList = (params: any) => request.get('/admin/logs/list', { params })
export const getUserList = (params: any) => request.get('/admin/users/list', { params })
export const getUserDetail = (id: number) => request.get(`/admin/users/${id}`)
export const updateUser = (id: number, data: any) => request.put(`/admin/users/${id}`, data)
export const deleteUser = (id: number) => request.delete(`/admin/users/${id}`)
export const getRoleList = () => request.get('/admin/roles/list')
export const saveRole = (data: any) => request.post('/admin/roles', data)
export const deleteRole = (id: number) => request.delete(`/admin/roles/${id}`)
export const getRoleMenus = (id: number) => request.get(`/admin/roles/${id}/menus`)
export const assignMenus = (id: number, menuIds: number[]) => request.put(`/admin/roles/${id}/menus`, menuIds)
export const getMenuTree = () => request.get('/admin/menus/tree')
export const saveMenu = (data: any) => request.post('/admin/menus', data)
export const deleteMenu = (id: number) => request.delete(`/admin/menus/${id}`)
export const getVocabList = (params: any) => request.get('/admin/vocab/list', { params })
export const saveVocab = (data: any) => request.post('/admin/vocab', data)
export const deleteVocab = (id: number) => request.delete(`/admin/vocab/${id}`)
export const getListeningList = (params: any) => request.get('/admin/listening/list', { params })
export const saveListening = (data: any) => request.post('/admin/listening', data)
export const getReadingList = (params: any) => request.get('/admin/reading/list', { params })
export const savePassage = (data: any) => request.post('/admin/reading/passage', data)
export const saveReadingQuestion = (data: any) => request.post('/admin/reading/question', data)
export const saveReadingVocab = (data: any) => request.post('/admin/reading/vocab', data)
export const getGrammarList = (params: any) => request.get('/admin/grammar/list', { params })
export const saveGrammar = (data: any) => request.post('/admin/grammar', data)
export const uploadAudio = (file: File) => { const fd = new FormData(); fd.append('file', file); return request.post('/admin/upload/audio', fd, { headers: { 'Content-Type': 'multipart/form-data' } }) }
export const uploadImage = (file: File) => { const fd = new FormData(); fd.append('file', file); return request.post('/admin/upload/image', fd, { headers: { 'Content-Type': 'multipart/form-data' } }) }
